(() => {
  const localKey = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
  const fixToday = () => document.querySelectorAll('.week-day').forEach(day => day.classList.toggle('today',day.dataset.date===localKey()));
  const observer=new MutationObserver(fixToday); observer.observe(document.querySelector('#weekGrid'),{childList:true}); fixToday(); setInterval(fixToday,500);

  // Voorraad en receptvoorstellen blijven in dezelfde gedeelde app-data als
  // boodschappen en recepten, zodat Oppie en Ienie steeds dezelfde kast zien.
  const app=window.oppieApp;
  app.data.pantry=app.data.pantry||[];
  const access=document.createElement('dialog');
  access.id='houseCodeDialog'; access.className='house-code-dialog';
  access.innerHTML=`<form id="houseCodeForm" class="modal small"><div class="house-code-icon">🏠</div><p class="eyebrow">OPPIE EN IENIE</p><h2>Welkom thuis</h2><p class="muted">Voer jullie huiscode in om de gedeelde app te openen.</p><label>Huiscode<input id="houseCodeInput" inputmode="numeric" autocomplete="one-time-code" maxlength="6" required placeholder="••••••" /></label><p id="houseCodeError" class="house-code-error" hidden>Die code klopt niet. Probeer het nog eens.</p><button class="primary wide" type="submit">Open de app</button></form>`;
  document.body.append(access);
  let householdCode=localStorage.getItem('oiHouseholdCode')||'';
  const showHouseCode=()=>{if(!householdCode)access.showModal();};
  document.querySelector('#houseCodeForm').addEventListener('submit',event=>{event.preventDefault();const code=document.querySelector('#houseCodeInput').value.trim();if(code!=='582267'){document.querySelector('#houseCodeError').hidden=false;return;}householdCode=code;localStorage.setItem('oiHouseholdCode',code);access.close();});
  showHouseCode();
  const pantry=document.createElement('section');
  pantry.id='pantryView'; pantry.className='view';
  pantry.innerHTML=`
    <div class="section-heading"><div><h2>Voorraad</h2></div></div>
    <div class="pantry-intro card"><div><strong>Koken met wat er al is</strong><p>Voeg producten toe die thuis liggen. Daarna bedenken we een passend recept.</p></div></div>
    <form id="pantryForm" class="pantry-form"><input id="pantryName" required autocomplete="off" placeholder="Bijv. pasta, tomaten, kikkererwten" /><input id="pantryAmount" autocomplete="off" placeholder="Hoeveel?" /><button class="secondary" type="submit">Toevoegen</button></form>
    <div id="pantryList" class="pantry-list"></div>
    <button id="generatePantryRecipe" class="primary wide pantry-generate" type="button">Bedenk een recept</button>
    <p id="pantryHint" class="muted pantry-hint">Voeg minimaal twee producten toe voor een voorstel.</p>
    <div class="inspiration-card card"><div><strong>Verrassingspan</strong><p>Geen idee voor vanavond? Laat je verrassen met een maaltijd.</p></div><button id="generateInspiration" class="secondary" type="button">Verras ons</button></div>
    <div id="pantryRecipe" class="pantry-recipe" hidden></div>`;
  document.querySelector('main').append(pantry);
  const nav=document.querySelector('.bottom-nav');
  const pantryButton=document.createElement('button'); pantryButton.className='nav-item'; pantryButton.dataset.view='pantryView'; pantryButton.innerHTML='<span class="nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M5 9.5h14l-1 10H6l-1-10Z"/><path d="M8.5 9.5V7a3.5 3.5 0 0 1 7 0v2.5M4 9.5h16"/></svg></span><span class="nav-label">Voorraad</span>';
  nav.append(pantryButton);

  function renderPantry(){
    const list=document.querySelector('#pantryList'), items=app.data.pantry||[];
    list.innerHTML=items.length?items.map(item=>`<div class="pantry-item"><div><strong>${app.esc(item.name)}</strong>${item.amount?`<small>${app.esc(item.amount)}</small>`:''}</div><button type="button" class="delete" data-remove-pantry="${item.id}" aria-label="Verwijder ${app.esc(item.name)}">×</button></div>`).join(''):'<p class="muted pantry-empty">Je voorraad is nog leeg. Begin met een paar producten die je in huis hebt.</p>';
    document.querySelector('#generatePantryRecipe').disabled=items.length<2;
    document.querySelector('#pantryHint').textContent=items.length<2?'Voeg minimaal twee producten toe voor een voorstel.':`${items.length} producten in huis — klaar voor een receptidee.`;
  }
  function recipeSteps(instructions){return String(instructions||'').split(/\s*(?:\d+[.)])\s*/).map(step=>step.trim()).filter(Boolean)}
  function showPantryRecipe(recipe,notice='Receptvoorstel op basis van jullie voorraad'){
    const card=document.querySelector('#pantryRecipe'); card.hidden=false; card.dataset.recipe=JSON.stringify(recipe);
    const steps=recipeSteps(recipe.instructions);const ingredients=(recipe.ingredients||[]).map(item=>`<span>${app.esc(item[0])}${item[1]?` <small>${app.esc(item[1])}</small>`:''}</span>`).join('');
    card.innerHTML=`<button type="button" class="surprise-close" data-close-surprise="pantryRecipe" aria-label="Sluit voorstel">×</button><p class="eyebrow">${notice.toUpperCase()}</p><h3>${app.esc(recipe.name)}</h3>${recipe.image?`<img class="pantry-recipe-image" src="${app.esc(recipe.image)}" alt="${app.esc(recipe.name)}" />`:''}<p class="pantry-recipe-note">${app.esc(recipe.note||'')}</p><div class="pantry-recipe-ingredients">${ingredients}</div><ol class="pantry-steps">${steps.map(step=>`<li>${app.esc(step)}</li>`).join('')}</ol><div class="pantry-recipe-actions"><button type="button" class="secondary" id="savePantryRecipe">Opslaan bij Recepten</button><button type="button" class="secondary" id="otherPantryRecipe">Andere optie</button></div>`;
  }
  function generatePantryRecipe(button,excludedRecipeName=''){const items=app.data.pantry||[];if(items.length<2)return;button.disabled=true;const originalLabel=button.textContent;button.textContent='Recept wordt bedacht…';app.generateRecipeWithAI(items,householdCode,excludedRecipeName?'alternatief':'voorraad',excludedRecipeName).then(recipe=>{recipe.id=app.uid();recipe.cook=recipe.cook||'both';recipe.image='';showPantryRecipe(recipe,excludedRecipeName?'Een andere optie met jullie voorraad':'Recept op basis van jullie voorraad');}).catch(error=>{document.querySelector('#pantryHint').textContent=error.message;}).finally(()=>{button.disabled=false;button.textContent=originalLabel;});}
  function generateInspiration(button){button.disabled=true;const originalLabel=button.textContent;button.textContent='Even kiezen…';app.generateRecipeWithAI([],householdCode,'inspiratie').then(recipe=>{recipe.id=app.uid();recipe.cook=recipe.cook||'both';recipe.image=recipe.image||'';showPantryRecipe(recipe,'Verrassingspan voor vanavond');}).catch(error=>{document.querySelector('#pantryHint').textContent=error.message;}).finally(()=>{button.disabled=false;button.textContent=originalLabel;});}
  document.querySelector('#pantryForm').addEventListener('submit',event=>{event.preventDefault();const name=document.querySelector('#pantryName').value.trim();if(!name)return;app.data.pantry.push({id:app.uid(),name,amount:document.querySelector('#pantryAmount').value.trim()});app.save();event.target.reset();renderPantry();});
  document.addEventListener('click',event=>{
    if(event.target.closest('[data-view="pantryView"]'))renderPantry();
    const closeSurprise=event.target.closest('[data-close-surprise]');if(closeSurprise){document.querySelector(`#${closeSurprise.dataset.closeSurprise}`).hidden=true;return;}
    const remove=event.target.closest('[data-remove-pantry]');if(remove){app.data.pantry=app.data.pantry.filter(item=>item.id!==remove.dataset.removePantry);app.save();renderPantry();return;}
    if(event.target.closest('#generatePantryRecipe')){generatePantryRecipe(event.target.closest('#generatePantryRecipe'));return;}
    if(event.target.closest('#generateInspiration')){generateInspiration(event.target.closest('#generateInspiration'));return;}
    if(event.target.closest('#otherPantryRecipe')){const currentRecipe=JSON.parse(document.querySelector('#pantryRecipe').dataset.recipe||'{}');generatePantryRecipe(event.target.closest('#otherPantryRecipe'),currentRecipe.name||'');return;}
    if(event.target.closest('#savePantryRecipe')){const recipe=JSON.parse(document.querySelector('#pantryRecipe').dataset.recipe||'null');if(!recipe)return;app.data.recipes.push(recipe);app.save();app.renderRecipes();document.querySelector('#pantryHint').textContent='Opgeslagen bij Recepten — klaar om in te plannen!';event.target.textContent='✓ Opgeslagen bij Recepten';event.target.disabled=true;}
  });
  renderPantry();

  // Baksels zijn gedeeld, net als de boodschappenlijst. Foto's worden als
  // compacte data-url bewaard; houd ze daarom beperkt om het delen vlot te houden.
  app.data.baking=app.data.baking||[];
  app.data.bakingFeedback=app.data.bakingFeedback||[];
  let pendingBakeImages=[];
  function bakeStars(stars){const value=Math.max(0,Math.min(5,Number(stars)||0)),full=Math.floor(value),half=value-full>=.5;return '★'.repeat(full)+(half?'½':'')+'☆'.repeat(5-full-(half?1:0));}
  function ratingOptions(){return [0,.5,1,1.5,2,2.5,3,3.5,4,4.5,5].map(value=>`<option value="${value}">${value?`${bakeStars(value)} — ${String(value).replace('.',',')}/5`:'Nog geen beoordeling'}</option>`).join('');}
  const baking=document.createElement('section');
  baking.id='bakingView'; baking.className='view';
  baking.innerHTML=`
    <div class="section-heading"><div><h2>Vegan bakken</h2></div></div>
    <section class="baking-inspiration card"><div><p class="eyebrow">VERS UIT DE BAKKERIJ</p><h3>Vegan bakverrassing</h3><p>Ontdek een hip, volledig vegan baksel dat nu populair is.</p></div><button id="generateBakingIdea" class="primary" type="button">Verras mij</button></section>
    <section class="baking-cake card"><div><strong>Taartenverrassing</strong><p>Alleen volledig vegan taarten, van klassiek tot trend.</p></div><button id="generateCakeIdea" class="secondary" type="button">Verras mij met taart</button></section>
    <div id="bakingSuggestion" class="baking-suggestion" hidden></div>
    <div class="baking-divider"><span>Mijn baksels</span></div>
    <form id="bakeForm" class="bake-form card"><label>Naam van je baksel<input id="bakeName" required placeholder="Bijv. citroenrolletjes" /></label><label>Foto's <span class="optional">optioneel, max. 5 foto's van 500 KB</span><input id="bakePhotos" type="file" accept="image/*" multiple /></label><div id="bakePhotoPreview" class="bake-photo-previews" hidden></div><label>Notities<textarea id="bakeNotes" required placeholder="Ingrediënten, bereidingswijze en wat je wilt onthouden"></textarea></label><div class="bake-ratings"><label>Oppie<select id="bakeOppieRating">${ratingOptions()}</select></label><label>Ienie<select id="bakeIenieRating">${ratingOptions()}</select></label></div><button class="secondary wide" type="submit">Bewaar bij mijn baksels</button></form>
    <div id="bakingList" class="baking-list"></div>`;
  document.querySelector('main').append(baking);
  const bakingButton=document.createElement('button'); bakingButton.className='nav-item'; bakingButton.dataset.view='bakingView'; bakingButton.innerHTML='<span class="nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M7 3.5h10v17H7z"/><path d="M5 8.5h14M9 12h6M9 15h6M10 3.5V2h4v1.5"/></svg></span><span class="nav-label">Bakken</span>';
  nav.append(bakingButton);

  const bakeRecipeText=recipe=>`Ingrediënten\n${(recipe.ingredients||[]).map(item=>`• ${item[0]}${item[1]?` — ${item[1]}`:''}`).join('\n')}\n\nBereiding\n${recipe.instructions||''}`;
  const bakePhotos=item=>item.photos?.length?item.photos:(item.image?[item.image]:[]);
  const bakeNotes=item=>item.notes??item.recipe??'';
  const bakeRatings=item=>item.ratings||{oppie:0,ienie:0};
  function renderBaking(){const list=document.querySelector('#bakingList'),items=app.data.baking||[];list.innerHTML=items.length?items.slice().reverse().map(item=>{const photos=bakePhotos(item),ratings=bakeRatings(item);return `<article class="bake-entry" data-edit-bake="${item.id}" role="button" tabindex="0">${photos[0]?`<img src="${app.esc(photos[0])}" alt="${app.esc(item.name)}" />`:''}<div class="bake-entry-copy"><strong>${app.esc(item.name)}</strong>${photos.length>1?`<small class="bake-photo-count">+${photos.length-1} foto's</small>`:''}<div class="bake-ratings-display"><span>Oppie: ${bakeStars(ratings.oppie)}</span><span>Ienie: ${bakeStars(ratings.ienie)}</span></div><p>${app.esc(bakeNotes(item))}</p></div><button type="button" class="bake-delete" data-remove-bake="${item.id}" aria-label="Verwijder ${app.esc(item.name)}" title="Verwijder baksel">×</button></article>`;}).join(''):'<p class="muted bake-empty">Hier komen de baksels die jullie hebben gemaakt.</p>';}
  function showBakingSuggestion(recipe){const card=document.querySelector('#bakingSuggestion');card.hidden=false;card.dataset.recipe=JSON.stringify(recipe);const ingredients=(recipe.ingredients||[]).map(item=>`<span>${app.esc(item[0])}${item[1]?` <small>${app.esc(item[1])}</small>`:''}</span>`).join('');card.innerHTML=`<button type="button" class="surprise-close" data-close-surprise="bakingSuggestion" aria-label="Sluit voorstel">×</button><p class="eyebrow">VEGAN BAKIDEE VAN NU</p><h3>${app.esc(recipe.name)}</h3>${recipe.image?`<img src="${app.esc(recipe.image)}" alt="${app.esc(recipe.name)}" />`:''}<p class="baking-trend">${app.esc(recipe.trend||'Populair nu')}</p><p class="pantry-recipe-note">${app.esc(recipe.note||'')}</p><div class="pantry-recipe-ingredients">${ingredients}</div><ol class="pantry-steps">${recipeSteps(recipe.instructions).map(step=>`<li>${app.esc(step)}</li>`).join('')}</ol><div class="baking-actions"><button id="useBakingSuggestion" class="secondary" type="button">Bewaar bij mijn baksels</button><button id="otherBakingIdea" class="secondary" type="button">Andere optie</button></div>`;}
  function generateBakingIdea(button,excludedRecipeName='',mode='bakken'){button.disabled=true;const originalLabel=button.textContent;button.textContent='Even zoeken…';const feedback=app.data.bakingFeedback.slice(-12).map(item=>`${item.type}: ${item.text}`).join(' | ');app.generateRecipeWithAI([],householdCode,mode,excludedRecipeName,feedback).then(recipe=>{recipe.id=app.uid();showBakingSuggestion(recipe);}).catch(error=>{document.querySelector('#bakingSuggestion').hidden=false;document.querySelector('#bakingSuggestion').textContent=error.message;}).finally(()=>{button.disabled=false;button.textContent=originalLabel;});}
  function previewBakePhotos(target,photos){target.hidden=!photos.length;target.innerHTML=photos.map((photo,index)=>`<img src="${app.esc(photo)}" alt="Voorbeeldfoto ${index+1}" />`).join('');}
  function readBakeFiles(files){const selected=Array.from(files||[]);if(selected.length>5){alert('Kies maximaal 5 foto's.');return Promise.resolve([]);}if(selected.some(file=>file.size>500*1024)){alert('Elke foto mag maximaal 500 KB zijn.');return Promise.resolve([]);}return Promise.all(selected.map(file=>new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file);})));}
  document.querySelector('#bakePhotos').addEventListener('change',async event=>{const photos=await readBakeFiles(event.target.files);if(!photos.length&&event.target.files?.length){event.target.value='';return;}pendingBakeImages=photos;previewBakePhotos(document.querySelector('#bakePhotoPreview'),photos);});
  document.querySelector('#bakeForm').addEventListener('submit',event=>{event.preventDefault();const name=document.querySelector('#bakeName').value.trim(),notes=document.querySelector('#bakeNotes').value.trim();if(!name||!notes)return;app.data.baking.push({id:app.uid(),name,notes,photos:pendingBakeImages,ratings:{oppie:+document.querySelector('#bakeOppieRating').value,ienie:+document.querySelector('#bakeIenieRating').value},createdAt:new Date().toISOString()});app.save();event.target.reset();pendingBakeImages=[];previewBakePhotos(document.querySelector('#bakePhotoPreview'),[]);renderBaking();});
  const bakeDialog=document.createElement('dialog');bakeDialog.id='bakeEditDialog';bakeDialog.innerHTML=`<form id="bakeEditForm" class="modal"><div class="modal-header"><div><p class="eyebrow">MIJN BAKSEL</p><h2>Baksel aanpassen</h2></div><button class="close" value="cancel">×</button></div><input id="editBakeId" type="hidden" /><label>Naam<input id="editBakeName" required /></label><label>Notities<textarea id="editBakeNotes" required></textarea></label><div class="bake-ratings"><label>Oppie<select id="editBakeOppieRating">${ratingOptions()}</select></label><label>Ienie<select id="editBakeIenieRating">${ratingOptions()}</select></label></div><label>Foto's toevoegen <span class="optional">max. 5 totaal, 500 KB per foto</span><input id="editBakePhotos" type="file" accept="image/*" multiple /></label><div id="editBakePhotoPreview" class="bake-photo-previews"></div><button class="primary wide" type="submit">Wijzigingen opslaan</button></form>`;document.body.append(bakeDialog);
  function openBakeEditor(id){const item=(app.data.baking||[]).find(bake=>bake.id===id);if(!item)return;const ratings=bakeRatings(item);document.querySelector('#editBakeId').value=id;document.querySelector('#editBakeName').value=item.name;document.querySelector('#editBakeNotes').value=bakeNotes(item);document.querySelector('#editBakeOppieRating').value=ratings.oppie||0;document.querySelector('#editBakeIenieRating').value=ratings.ienie||0;previewBakePhotos(document.querySelector('#editBakePhotoPreview'),bakePhotos(item));bakeDialog.showModal();}
  document.querySelector('#editBakePhotos').addEventListener('change',async event=>{const add=await readBakeFiles(event.target.files),item=(app.data.baking||[]).find(bake=>bake.id===document.querySelector('#editBakeId').value);if(!item||!add.length)return;const photos=[...bakePhotos(item),...add].slice(0,5);item.photos=photos;delete item.image;previewBakePhotos(document.querySelector('#editBakePhotoPreview'),photos);event.target.value='';});
  document.querySelector('#bakeEditForm').addEventListener('submit',event=>{event.preventDefault();const item=(app.data.baking||[]).find(bake=>bake.id===document.querySelector('#editBakeId').value);if(!item)return;item.name=document.querySelector('#editBakeName').value.trim();item.notes=document.querySelector('#editBakeNotes').value.trim();item.ratings={oppie:+document.querySelector('#editBakeOppieRating').value,ienie:+document.querySelector('#editBakeIenieRating').value};delete item.recipe;delete item.stars;app.save();bakeDialog.close();renderBaking();});
  document.addEventListener('click',event=>{const feedback=event.target.closest('[data-baking-feedback]');if(feedback){document.querySelector('#bakingSuggestion').dataset.feedbackType=feedback.dataset.bakingFeedback;document.querySelectorAll('[data-baking-feedback]').forEach(button=>button.classList.toggle('active',button===feedback));return;}if(event.target.closest('#saveBakingFeedback')){const type=document.querySelector('#bakingSuggestion').dataset.feedbackType||'opmerking',text=document.querySelector('#bakingFeedbackNote').value.trim()||JSON.parse(document.querySelector('#bakingSuggestion').dataset.recipe||'{}').name||'bakvoorstel';app.data.bakingFeedback.push({type,text,createdAt:new Date().toISOString()});app.data.bakingFeedback=app.data.bakingFeedback.slice(-20);app.save();event.target.textContent='✓ Voorkeur bewaard';}});
  new MutationObserver(()=>{const card=document.querySelector('#bakingSuggestion');if(card.hidden||card.querySelector('.baking-feedback'))return;const feedback=document.createElement('div');feedback.className='baking-feedback';feedback.innerHTML='<strong>Voor een volgende suggestie</strong><div><button type="button" class="secondary" data-baking-feedback="meer">Meer zoals dit</button><button type="button" class="secondary" data-baking-feedback="minder">Minder zoals dit</button></div><input id="bakingFeedbackNote" placeholder="Bijv. meer fruit, minder chocolade" /><button type="button" class="text-button" id="saveBakingFeedback">Bewaar voorkeur</button>';card.append(feedback);}).observe(document.querySelector('#bakingSuggestion'),{childList:true});
  document.addEventListener('click',event=>{if(event.target.closest('[data-view="bakingView"]'))renderBaking();const closeSurprise=event.target.closest('[data-close-surprise]');if(closeSurprise){document.querySelector(`#${closeSurprise.dataset.closeSurprise}`).hidden=true;return;}if(event.target.closest('#generateBakingIdea')){generateBakingIdea(event.target.closest('#generateBakingIdea'));return;}if(event.target.closest('#generateCakeIdea')){generateBakingIdea(event.target.closest('#generateCakeIdea'),'','taart');return;}if(event.target.closest('#otherBakingIdea')){const current=JSON.parse(document.querySelector('#bakingSuggestion').dataset.recipe||'{}');generateBakingIdea(event.target.closest('#otherBakingIdea'),current.name||'');return;}if(event.target.closest('#useBakingSuggestion')){const recipe=JSON.parse(document.querySelector('#bakingSuggestion').dataset.recipe||'null');if(!recipe)return;document.querySelector('#bakeName').value=recipe.name||'';document.querySelector('#bakeNotes').value=bakeRecipeText(recipe);pendingBakeImages=recipe.image?[recipe.image]:[];previewBakePhotos(document.querySelector('#bakePhotoPreview'),pendingBakeImages);document.querySelector('#bakeForm').scrollIntoView({behavior:'smooth',block:'start'});return;}const remove=event.target.closest('[data-remove-bake]');if(remove){app.data.baking=app.data.baking.filter(item=>item.id!==remove.dataset.removeBake);app.save();renderBaking();return;}const entry=event.target.closest('[data-edit-bake]');if(entry)openBakeEditor(entry.dataset.editBake);});
  const bakingStyle=document.createElement('style');bakingStyle.textContent=`
    .bottom-nav{grid-template-columns:repeat(7,minmax(0,1fr))}.baking-inspiration{display:flex;align-items:center;justify-content:space-between;gap:14px;padding:17px;margin-bottom:14px;background:linear-gradient(135deg,#fff4df,#f7ead6);border-color:#e8c891}.baking-inspiration h3{font-size:22px;margin:3px 0}.baking-inspiration p:not(.eyebrow){font-size:13px;color:var(--muted)}.baking-inspiration .primary{padding:11px 13px;white-space:nowrap}.baking-inspiration button:disabled{opacity:.55}.baking-suggestion{border:1px solid #e4c478;background:#fffaf0;border-radius:18px;padding:18px;margin-bottom:18px}.baking-suggestion h3{font-size:24px;line-height:1.18;margin:5px 0}.baking-suggestion img{display:block;width:100%;height:200px;object-fit:cover;border-radius:13px;margin:11px 0}.baking-trend{display:inline-block;background:#f6dfad;color:#785119;border-radius:999px;padding:6px 9px;font-size:12px;font-weight:800;margin:0 0 11px}.baking-divider{display:flex;align-items:center;gap:10px;color:var(--green);font-weight:800;margin:23px 0 12px}.baking-divider:before,.baking-divider:after{content:'';height:1px;background:var(--line);flex:1}.bake-form{display:grid;gap:10px;padding:15px;margin-bottom:14px}.bake-form label{font-size:13px;font-weight:700}.bake-form input,.bake-form textarea,.bake-form select{display:block;width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;margin-top:5px;font:16px inherit;background:#fff}.bake-form textarea{min-height:110px;resize:vertical}.bake-photo-preview{width:100%;max-height:220px;object-fit:cover;border-radius:12px;border:1px solid var(--line)}.baking-list{display:grid;gap:9px}.bake-entry{display:grid;grid-template-columns:64px 1fr auto;gap:11px;align-items:start;padding:12px;background:#fff;border:1px solid var(--line);border-radius:15px}.bake-entry>img{width:64px;height:64px;object-fit:cover;border-radius:11px}.bake-entry-copy{display:grid;gap:2px}.bake-entry-copy p{font-size:12px;color:var(--muted);white-space:pre-line;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.bake-stars{color:#d28b19;font-size:14px;letter-spacing:1px}.bake-empty{padding:5px 2px 18px}@media(min-width:650px){.bottom-nav{grid-template-columns:none}.baking-suggestion img{height:250px}}`;
  document.head.append(bakingStyle);
  const bakingControls=document.createElement('style');bakingControls.textContent='.pantry-recipe,.baking-suggestion{position:relative}.surprise-close{position:absolute;right:12px;top:12px;z-index:1;width:26px;height:26px;display:grid;place-items:center;border:0;border-radius:50%;background:rgba(255,255,255,.9);color:#8d978f;font:24px/1 system-ui;cursor:pointer}.surprise-close:hover{background:#f9e4df;color:var(--red)}.baking-cake{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 16px;margin-bottom:14px;background:#fffdf3;border-color:#e6d98e}.baking-cake strong{color:var(--green)}.baking-cake p{font-size:13px;color:var(--muted);margin-top:2px}.baking-cake .secondary{padding:10px 11px;font-size:12px;white-space:nowrap}.baking-cake button:disabled{opacity:.55}.baking-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:18px}.baking-actions .secondary{padding:12px 8px;font-size:13px;background:#fff}.bake-delete{width:26px;height:26px;display:grid;place-items:center;border:0;border-radius:50%;background:#f5f1ec;color:#957460;font:24px/1 system-ui;cursor:pointer}.bake-delete:hover{background:#f9e4df;color:var(--red)}';document.head.append(bakingControls);
  renderBaking();

  const bakingExtras=document.createElement('style');bakingExtras.textContent='.bake-photo-previews{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.bake-photo-previews img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:10px;border:1px solid var(--line)}.bake-ratings{display:grid;grid-template-columns:1fr 1fr;gap:10px}.bake-ratings-display{display:grid;gap:2px;color:#b8750e;font-size:12px;font-weight:700}.bake-photo-count{color:var(--muted)}.baking-feedback{margin-top:17px;padding-top:14px;border-top:1px solid #eadfca;display:grid;gap:8px}.baking-feedback strong{font-size:13px}.baking-feedback>div{display:flex;gap:7px}.baking-feedback .active{background:#f0f7d4;border-color:var(--green);color:var(--green)}.baking-feedback input{width:100%;border:1px solid var(--line);border-radius:9px;padding:9px;font:14px inherit}';document.head.append(bakingExtras);

  const game=document.createElement('section');
  game.id='gameView'; game.className='view';
  game.innerHTML=`
    <div class="section-heading"><div><p class="eyebrow">EVEN PAUZE</p><h2>Rendier-sprong</h2></div></div>
    <div class="reindeer-game">
      <p class="game-intro">Spring op tijd over de gansjes. Om de derde sprong komt er een klein eendje aan.</p>
      <div class="game-hud"><span>Score <strong id="gameScore">0</strong></span><span id="gameHighscoreLabel">Highscore <strong id="gameHighscore">0</strong></span></div>
      <div id="gameField" class="game-field" aria-label="Rendier-sprong spel">
        <div class="game-sun">☀️</div><div class="game-cloud cloud-one">☁️</div><div class="game-cloud cloud-two">☁️</div>
        <div class="forest forest-back">🌲　🌲　🌲　🌲</div><div class="forest forest-front">🌲　🌲　🌲</div>
        <div id="reindeer" aria-label="Rendier">🦌</div>
      </div>
      <button id="jumpButton" class="primary wide" type="button">Spring! ↑</button>
      <button id="restartGame" class="secondary wide" type="button" hidden>↻ Opnieuw spelen</button>
      <div id="highscoreForm" class="highscore-form" hidden><strong>🏆 Nieuwe highscore!</strong><label>Jouw naam<input id="highscoreName" maxlength="18" placeholder="Bijv. Oppie" /></label><button id="saveHighscoreName" type="button" class="secondary wide">Naam bewaren</button></div>
      <p id="gameMessage" class="muted game-message">Druk op A, de knop of de spatiebalk om te springen.</p>
    </div>`;
  document.querySelector('main').append(game);
  const b=document.createElement('button'); b.className='nav-item'; b.dataset.view='gameView'; b.innerHTML='<span class="nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="7" width="18" height="11" rx="4"/><path d="M8 10v5M5.5 12.5h5M16.5 11h.01M18.5 14h.01"/></svg></span><span class="nav-label">Spel</span>'; nav.append(b);

  const style=document.createElement('style'); style.textContent=`
    .reindeer-game{background:#fff;border:1px solid var(--line);border-radius:18px;padding:16px}.game-intro{font-size:14px;color:var(--muted);margin-bottom:12px}.game-hud{display:flex;justify-content:space-between;gap:10px;font-size:14px;margin-bottom:12px}.game-hud span{background:#f0f7d4;border-radius:11px;padding:8px 10px;color:var(--green)}
    .house-code-dialog .modal{text-align:center}.house-code-dialog h2{margin:3px 0 6px}.house-code-dialog .muted{margin-bottom:18px}.house-code-icon{width:54px;height:54px;display:grid;place-items:center;margin:0 auto 13px;border-radius:18px;background:#f0f7d4;font-size:27px}.house-code-dialog label{text-align:left}.house-code-dialog input{text-align:center;letter-spacing:9px;font-size:24px;font-weight:800}.house-code-error{margin:-4px 0 12px;color:var(--red);font-weight:700}
    .pantry-intro{padding:15px 16px;margin-bottom:12px}.pantry-intro p{font-size:13px;color:var(--muted);margin-top:2px}.pantry-form{display:grid;grid-template-columns:minmax(0,1fr) 90px auto;gap:7px;margin-bottom:12px}.pantry-form input{min-width:0;border:1px solid var(--line);border-radius:11px;padding:11px;font:14px inherit}.pantry-form .secondary{padding:0 11px;font-size:13px;white-space:nowrap}.pantry-list{display:grid;gap:7px;margin-bottom:14px}.pantry-item{display:flex;align-items:center;padding:11px 13px;background:#fff;border:1px solid var(--line);border-radius:13px}.pantry-item>div{display:grid;flex:1}.pantry-item small{font-size:12px;color:var(--muted)}.pantry-empty{padding:15px 2px}.pantry-generate:disabled{opacity:.45;cursor:not-allowed}.pantry-hint{text-align:center;margin:9px 0 13px}.inspiration-card{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:6px 0 14px;padding:15px 16px;background:#fffdf3;border-color:#e6d98e}.inspiration-card strong{color:var(--green)}.inspiration-card p{margin-top:2px;color:var(--muted);font-size:13px}.inspiration-card .secondary{flex:none;padding:10px 12px;font-size:13px;white-space:nowrap}.inspiration-card button:disabled{opacity:.55;cursor:not-allowed}.pantry-recipe{border:1px solid #b9d15f;background:#fbfdf4;border-radius:18px;padding:18px}.pantry-recipe h3{font-size:24px;line-height:1.18;margin:5px 0}.pantry-recipe-image{width:100%;height:190px;object-fit:cover;border-radius:13px;margin:10px 0 14px;background:#eef2eb}.pantry-recipe-note{color:var(--muted);font-size:14px;margin:0 0 14px}.pantry-recipe-ingredients{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:16px}.pantry-recipe-ingredients span{background:#edf6d6;color:var(--green);border-radius:999px;padding:6px 9px;font-size:13px;font-weight:700}.pantry-recipe-ingredients small{font:inherit;font-weight:500;opacity:.8}.pantry-steps{display:grid;gap:11px;margin:0;padding-left:21px;color:#46534d}.pantry-steps li{padding-left:3px;line-height:1.45}.pantry-recipe-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:18px}.pantry-recipe-actions .secondary{margin:0;background:#fff;padding:12px 10px;font-size:13px}.pantry-recipe-actions button:disabled{opacity:.55;cursor:not-allowed}
    .game-field{height:290px;position:relative;overflow:hidden;border-radius:16px;background:linear-gradient(#86d7fa 0 65%,#8fca68 65% 100%);margin-bottom:14px;isolation:isolate}.game-field:after{content:'';position:absolute;z-index:-1;inset:auto 0 0;height:35%;background:repeating-linear-gradient(110deg,rgba(71,139,66,.2) 0 24px,transparent 24px 48px);animation:ground-scroll .8s linear infinite}.game-field.snowing:before{content:'❄️　❅　❄️　❅　❄️　❅　❄️';position:absolute;z-index:8;inset:8px -30px auto;font-size:27px;white-space:nowrap;pointer-events:none;animation:snow-fall 2.7s linear infinite}.game-sun{position:absolute;right:18px;top:12px;font-size:48px;filter:drop-shadow(0 0 13px #ffe86e);animation:sun-glow 2s ease-in-out infinite alternate}.game-cloud{position:absolute;top:39px;font-size:34px;opacity:.82;animation:cloud-drift 16s linear infinite}.cloud-one{left:11%}.cloud-two{left:65%;top:78px;animation-duration:22s}.forest{position:absolute;white-space:nowrap;line-height:1;pointer-events:none}.forest-back{left:-3%;right:0;bottom:28px;font-size:112px;opacity:.83;z-index:0}.forest-front{left:-4%;right:0;bottom:26px;font-size:130px;opacity:.94;z-index:2}.game-obstacle{position:absolute;bottom:34px;z-index:3;line-height:1;will-change:transform}.game-obstacle.goose{font-size:43px}.game-obstacle.duck{font-size:28px;bottom:37px}.game-obstacle.bear{font-size:43px;bottom:34px}.game-bonus{position:absolute;z-index:6;font-size:46px;line-height:1;will-change:transform;filter:drop-shadow(0 2px 3px rgba(22,93,61,.22));animation:bonus-float .9s ease-in-out infinite alternate}.game-field #reindeer{position:absolute;left:42%;bottom:34px;z-index:4;font-size:68px;line-height:1;will-change:transform;transform:scaleX(-1);filter:drop-shadow(0 3px 1px rgba(0,0,0,.14))}.game-field #reindeer.jumping{animation:deer-jump .58s cubic-bezier(.3,.08,.55,1) forwards}.highscore-form{margin:12px 0;padding:12px;border:1px solid #b9d15f;border-radius:14px;background:#f0f7d4;color:var(--green)}.highscore-form label{display:block;font-size:13px;font-weight:700;margin:9px 0}.highscore-form input{display:block;width:100%;border:1px solid var(--line);border-radius:9px;padding:9px;margin-top:4px;font:inherit}.game-message{text-align:center;min-height:20px;margin-top:11px}.game-field.game-over{filter:saturate(.7)}
    @keyframes deer-jump{0%,100%{transform:scaleX(-1) translateY(0)}48%{transform:scaleX(-1) translateY(-142px)}58%{transform:scaleX(-1) translateY(-142px)}}@keyframes ground-scroll{to{background-position:-48px 0}}@keyframes cloud-drift{from{transform:translateX(0)}to{transform:translateX(-110px)}}@keyframes bonus-float{to{margin-top:-8px}}@keyframes snow-fall{to{transform:translate(-40px,270px)}}@keyframes sun-glow{to{filter:drop-shadow(0 0 23px #fff09b)}}
  `; document.head.append(style);

  const field=document.querySelector('#gameField'), deer=document.querySelector('#reindeer'), scoreEl=document.querySelector('#gameScore'), highscoreEl=document.querySelector('#gameHighscore'), highscoreLabel=document.querySelector('#gameHighscoreLabel'), highscoreForm=document.querySelector('#highscoreForm'), highscoreName=document.querySelector('#highscoreName'), saveHighscoreName=document.querySelector('#saveHighscoreName'), message=document.querySelector('#gameMessage'), jumpButton=document.querySelector('#jumpButton'), restart=document.querySelector('#restartGame');
  const highscoreKey='oppieEnIenieRendierHighscore', highscoreNameKey='oppieEnIenieRendierHighscoreName'; let highscore=Number(localStorage.getItem(highscoreKey)||0), highscoreOwner=localStorage.getItem(highscoreNameKey)||''; const renderHighscore=()=>{highscoreEl.textContent=highscore;highscoreLabel.firstChild.textContent=highscoreOwner?`${highscoreOwner}: `:'Highscore ';}; renderHighscore();
  let score=0,jumping=false,gameOver=false,lastFrame=0,lastSpawn=0,lastBonus=0,playTime=0,obstacleCount=0,obstacles=[],bonuses=[],rafId;
  const active=()=>document.querySelector('#gameView').classList.contains('active');
  const setScore=value=>{score=value;scoreEl.textContent=score;if(score>highscore){highscore=score;localStorage.setItem(highscoreKey,String(highscore));renderHighscore();highscoreForm.hidden=false;}};
  function spawnObstacle(){
    obstacleCount++; const kind=obstacleCount%10===0?'bear':obstacleCount%3===0?'duck':'goose'; const obstacle=document.createElement('div'); obstacle.className=`game-obstacle ${kind}`; obstacle.textContent=kind==='bear'?'🧸':kind==='duck'?'🦆':'🪿'; obstacle.style.left=`${field.clientWidth+24}px`; field.append(obstacle); obstacles.push({el:obstacle,x:field.clientWidth+24,passed:false});
  }
  function spawnBonus(){
    const amount=1+Math.floor(Math.random()*3);
    for(let i=0;i<amount;i++){
      const bonus=document.createElement('div'); bonus.className='game-bonus'; bonus.textContent='💤'; bonus.style.left=`${field.clientWidth+20+i*54}px`; bonus.style.bottom=`${92+Math.round(Math.random()*86)}px`; field.append(bonus); bonuses.push({el:bonus,x:field.clientWidth+20+i*54});
    }
  }
  function endGame(){gameOver=true;field.classList.add('game-over');restart.hidden=false;message.textContent=`Raak! Je score is ${score}. ${score===highscore&&score>0?'Nieuwe highscore! 🏆':'Probeer nog een keer.'}`;}
  function jump(){if(!active()||jumping||gameOver)return;jumping=true;deer.classList.remove('jumping');void deer.offsetWidth;deer.classList.add('jumping');setTimeout(()=>{jumping=false;deer.classList.remove('jumping');},580);}
  function reset(){obstacles.forEach(item=>item.el.remove());bonuses.forEach(item=>item.el.remove());obstacles=[];bonuses=[];setScore(0);gameOver=false;jumping=false;playTime=0;obstacleCount=0;lastSpawn=0;lastBonus=0;field.classList.remove('game-over','snowing');restart.hidden=true;highscoreForm.hidden=true;message.textContent='Druk op de knop of de spatiebalk om te springen.';}
  function frame(time){
    const delta=Math.min(40,time-lastFrame||16);lastFrame=time;
    if(active()&&!gameOver){
      playTime+=delta; const speed=3.35+Math.min(playTime/1000*.16,7); const spawnGap=Math.max(600,1450-playTime/1000*24);
      if(!lastSpawn||time-lastSpawn>spawnGap){spawnObstacle();lastSpawn=time;}
      if(!lastBonus||time-lastBonus>5000+Math.random()*4500){spawnBonus();lastBonus=time;}
      const deerBox=deer.getBoundingClientRect();
      obstacles=obstacles.filter(item=>{
        item.x-=speed*(delta/16);item.el.style.transform=`translateX(${item.x-field.clientWidth-24}px)`;
        const box=item.el.getBoundingClientRect();
        if(!item.passed&&box.right<deerBox.left){item.passed=true;setScore(score+1);}
        if(!jumping&&box.right>deerBox.left+8&&box.left<deerBox.right-10&&box.bottom>deerBox.top+30){endGame();}
        if(item.x<-100){item.el.remove();return false;}return true;
      });
      bonuses=bonuses.filter(item=>{item.x-=speed*.72*(delta/16);item.el.style.transform=`translateX(${item.x-field.clientWidth-20}px)`;const box=item.el.getBoundingClientRect();if(jumping&&box.right>deerBox.left&&box.left<deerBox.right&&box.bottom>deerBox.top&&box.top<deerBox.bottom){item.el.remove();setScore(score+3);message.textContent='💤 Gevangen! +3 punten';return false;}if(item.x<-80){item.el.remove();return false;}return true;});
      field.classList.toggle('snowing',score>=50);
    }
    rafId=requestAnimationFrame(frame);
  }
  jumpButton.addEventListener('click',jump);restart.addEventListener('click',reset);saveHighscoreName.addEventListener('click',()=>{highscoreOwner=highscoreName.value.trim();localStorage.setItem(highscoreNameKey,highscoreOwner);renderHighscore();highscoreForm.hidden=true;});
  document.addEventListener('keydown',event=>{if((event.code==='Space'||event.code==='ArrowUp')&&active()){event.preventDefault();jump();}});
  document.addEventListener('click',event=>{if(event.target.closest('[data-view="gameView"]')){lastNap=performance.now();}});
  rafId=requestAnimationFrame(frame);
})();
