(() => {
  const localKey = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
  const fixToday = () => { document.querySelectorAll('.week-day').forEach(day => day.classList.toggle('today',day.dataset.date===localKey())); };
  const observer=new MutationObserver(fixToday); observer.observe(document.querySelector('#weekGrid'),{childList:true}); fixToday(); setInterval(fixToday,500);

  const game=document.createElement('section'); game.id='gameView'; game.className='view'; game.innerHTML=`<div class="section-heading"><div><p class="eyebrow">EVEN PAUZE</p><h2>Rendier-sprong</h2></div></div><div class="reindeer-game"><p>Help het rendier met zijn grote gewei over de gansjes.</p><div class="game-score">Score: <strong id="gameScore">0</strong></div><div id="gameField" class="game-field"><div id="reindeer">🦌</div><div id="goose">🪿</div></div><button id="jumpButton" class="primary wide">Spring! ↑</button><p id="gameMessage" class="muted">Gebruik de knop of spatiebalk.</p></div>`;
  document.querySelector('main').append(game);
  const nav=document.querySelector('.bottom-nav'); const b=document.createElement('button'); b.className='nav-item';b.dataset.view='gameView';b.innerHTML='<span>🎮</span>Spel';nav.append(b);
  const style=document.createElement('style');style.textContent=`.reindeer-game{background:#fff;border:1px solid var(--line);border-radius:18px;padding:16px}.game-score{margin:12px 0;font-size:15px}.game-field{height:220px;position:relative;overflow:hidden;border-radius:14px;background:linear-gradient(#bfe7ff 0 66%,#99c86c 66%);margin-bottom:13px}.game-field:before{content:'☁️     ☁️';position:absolute;top:18px;left:12px;font-size:25px}.game-field:after{content:'🌲  🌲   🌲';position:absolute;bottom:28px;right:0;font-size:28px}.game-field div{position:absolute;bottom:30px;font-size:54px;z-index:1}#reindeer{left:22px;transition:bottom .18s;animation:reindeer-run 3.5s ease-in-out infinite alternate}#reindeer.jump{bottom:115px}#goose{right:14px}@keyframes reindeer-run{0%{left:22px;transform:scaleX(1)}49%{transform:scaleX(1)}51%{transform:scaleX(-1)}100%{left:calc(100% - 78px);transform:scaleX(-1)}}`;
  document.head.append(style);
  let score=0, jumping=false; const deer=document.querySelector('#reindeer'), goose=document.querySelector('#goose'), scoreEl=document.querySelector('#gameScore'), msg=document.querySelector('#gameMessage');
  function jump(){if(jumping)return;jumping=true;deer.classList.add('jump');score++;scoreEl.textContent=score;setTimeout(()=>{deer.classList.remove('jump');jumping=false},420)}
  document.querySelector('#jumpButton').onclick=jump;document.addEventListener('keydown',e=>{if(e.code==='Space'&&document.querySelector('#gameView').classList.contains('active')){e.preventDefault();jump()}});
  setInterval(()=>{if(!document.querySelector('#gameView').classList.contains('active'))return;const a=deer.getBoundingClientRect(),c=goose.getBoundingClientRect();if(a.right>c.left&&a.left<c.right&&a.bottom>c.top&&!jumping){score=0;scoreEl.textContent='0';msg.textContent='Oei, een gansje! Probeer opnieuw.';}},100);
})();
